export const DEFAULT_WORKER = {
  name: "Ravi Kumar",
  phone: "+91 98765 43210",
  upi: "ravikumar@upi",
  platform: "swiggy",
  zone: "hyd-old",
  hoursPerDay: 10,
  avgDailyIncome: 750,
  claims: 0,
  season: "monsoon",
  coverage: "standard",
  premium: 89,
  maxPayout: 2700,
  riskScore: 72,
};
